### ISSUE TITLE
Shouldn't an authentication failure return status 401 as well? 

### ISSUE THREAD

**Issue by sk91** [jaredhanson/passport-http#12]

**Comment by gnuton** [comment]
why this has been closed? is it still valid?

**Comment by gnuton** [comment]
ok I guess this has been cloased because the callback you pass to the authorization method gets an error when there is an auth failure. In this case you can throw 401

**Comment by sk91** [comment]
@gnuton sorry, don't remember exactly why I closed it. I fixed it for my self and made a pull request:

https://github.com/jaredhanson/passport-http/pull/13

**Comment by sk91** [comment]
But it was ignored for more than 5 years ...
