### ISSUE TITLE
Custom error code

### ISSUE THREAD

**Issue by diego-betto** [jaredhanson/passport-http#55]
Hi,
any way to send custom error codes? Something like

```
passport.use(new BasicStrategy(
  function(userid, password, done) {
    User.findOne({ username: userid }, function (err, user) {
      if (err) { return done(err); }
      if (!user) { return done(null, false,401); }
      if (!user.verifyPassword(password)) { return done(null, false,403); }
      return done(null, user);
    });
  }
));
```

so for example
- !user => 401
- incorrect password => 403

Any clue?

Thank you

**Comment by jaredhanson** [comment]
No.  Both of those conditions should be a `401`.  Why do you want to change it?

**Comment by diego-betto** [comment]
Since the customer app needs these codes

**Comment by jaredhanson** [comment]
Fail with an error, and respond with the status code in your error hander.

```
if (!user.verifyPassword(password)) {
  var err = new Error('Forbidden');
  err.status = 403;
  return done(err);
}
```

**Comment by diego-betto** [comment]
Nice works like a charm, changed a little bit since using Restify 
error.status => error.statusCode

Thank you!
