### ISSUE TITLE
PLEASE NOMINATE MAINTAINERS

### ISSUE THREAD

**Issue by lonix1** [jaredhanson/passport-http#81]
@jaredhanson 

This is a great library, and there are many awesome PRs waiting to be merged. You obviously need some help to take this library forward, and it seems from discussions in the issues that many want to help.

Don't let this package die, it's heavily used, and so good!

Please nominate one or two people to help maintain this? You could maybe choose those with the most PRs, as they would be most familiar with your code base.

Please let us know whether you like/hate this idea?

**Comment by gnuton** [comment]
if you do so please do no nominate people that you do not trust.

**Comment by lonix1** [comment]
Dead project
